services:
  postgres:
    image: postgres:15
    container_name: book-tracker-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./containers_data/db/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  fastapi:
    container_name: book-tracker-fastapi
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        ./wait-for-it.sh postgres:5432 -t 60 --
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload --timeout-keep-alive 600
      "
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/code
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/code
    restart: on-failure
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
