[build-system]
requires = [
    "setuptools >= 35.0.2",
    "setuptools_scm >= 2.0.0, <3"
]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py310']  # it must be 3.10
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.ruff_cache
  | \.venv
  | _build
  | build
  | migrations
  | dist
  | venv
  | containers_data
)/
'''

# https://beta.ruff.rs/docs/configuration/
[tool.ruff]
select = [
    "E",  # pycodestyle error
    "F",  # pyflakes
    "T20",  # flake8-print
    "UP",  # pyupgrade
    "W",  # pycodestyle warnings
]

ignore = [
    'E501', #  Line too long
    'E731', #  Do not assign a `lambda` expression, use a `def`
    'F541', #  f-string without any placeholders
    'E741', #  Ambiguous variable name
    'UP017', # Use `datetime.UTC` alias
    "T201",  # print
    "E712",  # Comparison to `True` should be `cond is True`

]

exclude = [
    '.git',
    'alembic',
    'migrations',
    'scripts',
    'stubs',
    'venv',
]

target-version = "py311"

[tool.ruff.per-file-ignores]
# These files are generated by django and should probably not be modified
"**/create_dummy_instances.py" = ["F401"]

